{{- range .Values.microservices }}
  {{- $microservice := . }}
{{- $labels := dict "app.kubernetes.io/instance" (printf "%s-server" $microservice.name | lower) "app.kubernetes.io/name" (printf "%s-server" $microservice.name | lower) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ $labels | toYaml | nindent 4 }}
  name: {{ $microservice.name | lower }}-server
  namespace: {{ $.Values.global.namespace }}
spec:
  {{- with .progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- if not .scaledObject.enabled }}
  replicas: {{ .replica }}
  {{- end }}
  revisionHistoryLimit: {{ .revisionHistoryLimit | default 3 }}
  selector:
    matchLabels: {{ $labels | toYaml | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $microservice.name | lower }}-server
        app.kubernetes.io/name: {{ $microservice.name | lower }}-server
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
        - name: {{ $microservice.name | lower }}
          image: "{{ $.Values.global.ecr }}/{{ .ecrName }}:{{ .imageTag }}"
          imagePullPolicy: Always
          {{- with .command }}
          command:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .ports }}
          ports: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .startupProbe.enabled }}
          {{- include "probe" (dict "type" "startupProbe" "enabled" .startupProbe.enabled "method" .startupProbe.method "port" .startupProbe.port "path" .startupProbe.path "command" .startupProbe.command "custom" .startupProbe.custom "initialDelaySeconds" .startupProbe.initialDelaySeconds "periodSeconds" .startupProbe.periodSeconds "successThreshold" .startupProbe.successThreshold "failureThreshold" .startupProbe.failureThreshold "timeoutSeconds" .startupProbe.timeoutSeconds ) | nindent 10 }}
          {{- end }}
          {{- if .readinessProbe.enabled }}
          {{- include "probe" (dict "type" "readinessProbe" "enabled" .readinessProbe.enabled "method" .readinessProbe.method "port" .readinessProbe.port "path" .readinessProbe.path "command" .readinessProbe.command "custom" .readinessProbe.custom "initialDelaySeconds" .readinessProbe.initialDelaySeconds "periodSeconds" .readinessProbe.periodSeconds "successThreshold" .readinessProbe.successThreshold "failureThreshold" .readinessProbe.failureThreshold "timeoutSeconds" .readinessProbe.timeoutSeconds ) | nindent 10 }}
          {{- end }}
          {{- if .livenessProbe.enabled }}
          {{- include "probe" (dict "type" "livenessProbe" "enabled" .livenessProbe.enabled "method" .livenessProbe.method "port" .livenessProbe.port "path" .livenessProbe.path "command" .livenessProbe.command "custom" .livenessProbe.custom "initialDelaySeconds" .livenessProbe.initialDelaySeconds "periodSeconds" .livenessProbe.periodSeconds "successThreshold" .livenessProbe.successThreshold "failureThreshold" .livenessProbe.failureThreshold "timeoutSeconds" .livenessProbe.timeoutSeconds ) | nindent 10 }}
          {{- end }}
          {{- include "resourceRequest" . | nindent 10 }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: "Asia/Singapore"
          {{- with .env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .terminationMessagePath }}
          terminationMessagePath: {{ . }}
          {{- end }}
          {{- with .terminationMessagePolicy }}
          terminationMessagePolicy: {{ . }}
          {{- end }}
          {{- with .workingDir }}
          workingDir: {{ . }}
          {{- end }}
      {{- with .dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 15}}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}