{{- range .Values.microservices }}
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ $.Values.global.namespace }}
  name: {{ .name | lower }}-ingress
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .ingress.ingressClassName | default "alb" }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .ingress.backendService }}
            port:
              number: {{ .ingress.port }}
{{- end }}
---
{{- end }}