{{- if .Values.global.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ $.Values.global.namespace }}
type: Opaque
data:
  VAULT_TOKEN: {{ $.Values.global.secret.token }}
{{- end }}